#!/bin/bash

#%# family=auto
#%# capabilities=autoconf
PATH="/misc/bin:$PATH"
state="$MUNIN_PLUGSTATE/lanwide.status"				# cache status output in this file

do_autoconf()  {
   choice=(yes no)
   type -t signal awk > /dev/null
   echo "${choice[$?]}"
}

do_config()  {
   touch -d NOW-2min "$state.ref"				# reference time file: timestamp 2 minutes ago
   [[ $state -ot $state.ref ]] &&				# cached status file needs renewal if older than that
   signal @munin status > $state				# renew cached status when older than reference file 
cat << EOF
graph_title https://github.com/Bushmills/-multi-host-munin-plugins
graph_vlabel number of processes
graph_category multihost
graph_args --base 1000 -l 0
graph_scale no
EOF
awk '$2 == "processes" { print $1 ".label", $1
                         print $1 ".draw AREASTACK" }' $state
}

do_fetch()  {
   awk '$2 == "processes" { print $1 ".value", $4 }' $state
}

do_${1:-fetch}
exit 0
